name: Update this repo's README

on:
  schedule:
    # Once a day at 8 AM
    - cron: * * * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://javilopezg.com/category/seccion/tecnologia/feed/
          readme-section: feed
          empty-commits: false
          max: 7
          template: "* {{title}} -> {{description}}"
